CREATE SCHEMA IF NOT EXISTS TENANT_A;
SET SCHEMA TENANT_A;
create table MessageEntry (id bigint generated by default as identity, created timestamp not null, message varchar(100), primary key (id));

CREATE SCHEMA IF NOT EXISTS TENANT_B;
SET SCHEMA TENANT_B;
create table MessageEntry (id bigint generated by default as identity, created timestamp not null, message varchar(100), primary key (id));

--PUBLIC schema holds only application metadata - the tenant table
SET SCHEMA PUBLIC;
create table Tenant (name varchar(255) not null, schemaName varchar(255) not null, password varchar(255) not null, primary key (name));
insert into Tenant (name, schemaName, password) values ('Tenant_A', 'TENANT_A', 'lorem');
insert into Tenant (name, schemaName, password) values ('Tenant_B', 'TENANT_B', 'ipsum');
