CREATE SCHEMA IF NOT EXISTS TENANT_ALICE;
SET SCHEMA TENANT_ALICE;
create table TodoEntry (id bigint generated by default as identity, created timestamp not null, text varchar(100), primary key (id));

CREATE SCHEMA IF NOT EXISTS TENANT_BOB;
SET SCHEMA TENANT_BOB;
create table TodoEntry (id bigint generated by default as identity, created timestamp not null, text varchar(100), primary key (id));

--PUBLIC schema holds only application metadata - the tenant table
SET SCHEMA PUBLIC;
create table Tenant (name varchar(255) not null, schemaName varchar(255) not null, password varchar(255) not null, primary key (name));
insert into Tenant (name, schemaName, password) values ('Alice', 'TENANT_ALICE', 'lorem');
insert into Tenant (name, schemaName, password) values ('Bob', 'TENANT_BOB', 'ipsum');
